file_asr_no_socket/server/forms.py
'''사용자 데이터(.mp3) 수신을 위한 form 정의'''

from flask_wtf import FlaskForm
from wtforms import MultipleFileField
from wtforms.validators import DataRequired # 데이터가 있을 때만 보내주고, 없으면 에러 (분석할 음성 파일을 안보내서)

class FileUploadForm(FlaskForm):
    '''사용자로부터 파일을 전송받을 폼'''
    # 1st: label
    files = MultipleFileField(
        '첨부파일',
        validators=[DataRequired()]
    )

file_asr_no_socket/server/__init__.py
import config
from flask import Flask
from ai_asr.inference import WhisperInference

whisper = WhisperInference()

def create_app() -> Flask:
    '''서비스용 앱 생성'''
    app = Flask(__name__) # __name__ : server/ 폴더명
    app.config.from_object(config)
    
    # Blueprint 등록
    from .views import main_views
    from .views import asr_file_views
    app.register_blueprint(main_views.bp) # 서버가 알 수 있게 등록
    app.register_blueprint(asr_file_views.bp) # 서버가 알 수 있게 등록
    
    
    return app

file_asr_no_socket/server/views/asr_file_views.py
import os
from datetime import datetime
from flask import (
    Blueprint,
    jsonify, 
    render_template,
    request,
)
from werkzeug.utils import secure_filename
from config import UPLOAD_FILE_DIR
from server.forms import FileUploadForm # 서버 입장에서는 path가 server/ 부터 시작
from server import whisper
 
bp = Blueprint('asr_file', __name__, url_prefix='/asr_file') 

@bp.route('/') # / = /asr_file
def index():
    '''메인 페이지'''
    form = FileUploadForm()
    return render_template(
        'asr_file.html',
        form=form, # 파라미터명을 asr_file.html에 form.csrf_token 즉 form과 똑같이
    )

@bp.route('/upload/<user_id>', methods=['POST'])
def upload(user_id):
    # 파일 저장
    print(f'user_id: {user_id}')
    print('upload func working...')
    
    # 서버에 파일 저장
    user_upload_dir = os.path.join(UPLOAD_FILE_DIR, user_id)
    if not os.path.exists(user_upload_dir):
        os.mkdir(user_upload_dir)
    
    files = request.files.getlist('file') # 1st: attach_file_handler_no_socketio.js saveFilesToForm()에서 file라는 키값으로 append해서
    for file in files:
        print(f'file.name: {file.name}')
        prefix_name = f"{datetime.now().strftime('%y%m%d_%H_%M_%S.%f')}_." # ex. 20280623_00_12_34.327_.
        safe_filename = prefix_name + secure_filename(file.filename)
        print(f'safe_filename: {safe_filename}')
        file.save(os.path.join(user_upload_dir, safe_filename))
    return {
        'status': 'ok'
    }

@bp.route('/process', methods=['POST'])
def process():
    # user_id 추출
    user_id = request.json['user_id']
    print(f'user_id in process: {user_id}')
    if not user_id:
        return jsonify({
                'status': "fail",
                'contents': '사용자 식별에 실패했습니다.\n다시 시도해 주세요'
            })
    
    # 업로드 된 음성 파일 가져오기
    target_dir = os.path.join(UPLOAD_FILE_DIR, user_id)
    audio_files = os.listdir(target_dir)
    if len(audio_files) == 0:
        return jsonify({
                'status': "fail",
                'contents': '서버에 처리할 파일이 없습니다.\n다시 시도해 주세요'
            })
    # ASR 인공지능 수행
    result_dic = {}
    result_dic['length'] = len(audio_files)
    for idx, audio in enumerate(audio_files):
        # transcript = 'OpenAI whisper에서 처리한 문자열 겨로가'
        target_file = os.path.join(target_dir, audio)
        transcript = whisper.inference(target_file)
        transcript = transcript.replace('/', '') 
        transcript = transcript.replace('. ', '.\n\n') 
        
        result_dic[f'{idx}'] = transcript
    print(f'result_dic: {result_dic}')
    return jsonify(result_dic)

file_asr_no_socket/server/views/main_views.py
from flask import (
    Blueprint, # 웹에 라우팅이 많으면 발생할 순환참조 문제 (서로가 서로를 파일 참조/import)로 인한 에러 방지
    render_template,
)
 
bp = Blueprint('main', __name__, url_prefix='/') # 1st: 별명

@bp.route('/')
def index():
    '''메인 페이지'''
    return render_template('main.html')

file_asr_no_socket/server/templates/asr_file.html
{% extends "base.html" %}

{% block content %}
<script src="/static/js/attach_file_handler_no_socketio.js"></script>

<div class="row">
    <p class"text-start my-3">
        안녕하세요, 딥러닝 분석 시스템입니다.
    </p>
</div>

<a href="#" class="btn btn-outline-primary btn-sm my-3" 
    id="new-task-btn" hidden>새로운 파일 처리</a>

<!-- 파일 첨부 영역 -->
<div class="row">
    <div class="container m-3" id="attach_area">
        <form method="post" enctype="multipart/form-data" id="form">
            {{ form.csrf_token }}
            <div class="mb-3">
                <label for="formFile" class="form-label">
                    분석할 파일을 선택해 주세요
                </label>
                <input class="form-control" 
                    type="file" id="formfile"
                    onchange="addFile(this);"
                    multiple>
            </div>
            <!-- 첨부된 파일을 화면에 시현 -->
            <div class="mb-3 mx-1 row">
                <div class="row" id="attached-file-list" hidden>
                    첨부된 파일 목록
                </div>
                <div>
                    <!-- 첨부된 파일 이름들... -->
                    <div class="file-list"></div>
                </div>
            </div>
            <a href="#" class="btn btn-outline-primary btn-sm" id="submit_files">서버 전송하기</a>
            <a href="#" class="btn btn-outline-primary btn-sm" id="clear-content-btn">화면 초기화</a>
        </form>
    </div>
</div>

<!-- Progressbar 시현 영역 - upload -->
<div class="container" id="p_par_area_upload" hidden>
    <p>파일을 업로드 합니다 ^^, 잠시만 기다려 주세요</p>
    <div class="spinner-grow text-primary" role="status">
        <span class="sr-only"></span>
    </div>
</div>

<!-- Progressbar 시현 영역 - server process -->
<div class="container" id="p_par_area_process" hidden>
    <p>업로드 완료!!!</p>
    <p>서버 처리중입니다. 잠시만 기다려 주세요...</p>
    <div class="spinner-grow text-danger" role="status">
        <span class="sr-only"></span>
    </div>
</div>

<!-- 서버 처리 결과 시현 영역 -->
<div class="row" id="result_text_area" hidden>
    <div>
        <p>서버 처리 결과입니다.</p>
    </div>
    <div class="form-floating">
        <textarea 
            class="form-control"
            placeholder="나중에 필요하면 여기에 기록"
            style="height: 300px;"
            id="floatingTextarea2"></textarea>
        <label for="floatingTextarea2" id="textarea_label">딥러닝 작업이 긑나면 여기에 결과가 출력됩니다.</label>        
    </div>
</div>


{% endblock %}

file_asr_no_socket/server/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ACIN Academy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" 
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" 
        crossorigin="anonymous"></script>
</head>    
<body>
    <div class="container">
        <div class="row my-3">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <!-- navbar area -->
                <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
                    <div class="container-fluid">
                        <!-- href: 별명이 main인 blueprint -->
                        <a class="navbar-brand" href="{{ url_for('main.index') }}">ACIN</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="{{ url_for('asr_file.index') }}">음성파일 AI</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">실시간ASR</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">준비중</a>
                            </li>
                            <li class="nav-item dropdown">
                                <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dropdown link
                                    </a> -->
                                    <a class="nav-link dropdown-toggle" 
                                href="#" 
                                role="button" 
                                data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown link
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        </ul>
                    </div>
                    </div>
                    
                </nav>
                <div class="row">
                    <div class="container my-3">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="col-sm-1"></div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
</script>
</body>
</html>

file_asr_no_socket/server/templates/main.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <p class="text-start my-3">안녕하세요. 딥러닝 분석 서비스입니다.</p>
</div>
<div class="row">
    <p class="text-start my-3">상단 메뉴를 이용해 서비스를 사용해주세요.</p>
</div>
{% endblock %}